# Generated by Django 4.2 on 2024-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweetphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
